version: '3.9'
services:
  cockroach:
    image: cockroachdb/cockroach:v21.1.7
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - cockroach

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  cockroach-data: